* Prepare stimuli
** Spelling tests
*** Prepare words
     #+begin_src python :exports both :session words :results output
       from stimpool.words import WordPool
     #+end_src

     #+RESULTS:

    Prepare the words that will be used by the spelling tests.
**** Clean initial database
     This is done using stimpool which was developed for this project.
***** Get word pool
      This extracts the base word for each word by removing the suffix indicators.
     #+begin_src python :exports both :session words :results output
       word_pool = WordPool()
       print(word_pool.words.size)
       print(word_pool.words.head())
     #+end_src

     #+RESULTS:
     : 55457
     : 0           abs
     : 1          adsl
     : 2        adolfo
     : 3        adrián
     : 4    afganistán
     : Name: words, dtype: object

***** Select words without accented characters
      We don't want words that have accented characters because that adds a layer of complexity
      to spelling tasks because requires participants to press commands in order to type these
      characters.

      #+begin_src python :exports both :session words :results output
        word_pool.select_words_without_accented_characters()
        print(word_pool.words.size)
        print(word_pool.words.head())
      #+end_src

      #+RESULTS:
      : 46801
      : 0        abs
      : 1       adsl
      : 2     adolfo
      : 5    aguilar
      : 6      aitor
      : Name: words, dtype: object

***** Select words of more than 1 letter
      Just in case there are any

      #+begin_src python :exports both :session words :results output
        word_pool.select_words_of_length(min_len=2)
        print(word_pool.words.size)
        print(word_pool.words.head())
      #+end_src

      #+RESULTS:
      : 46794
      : 0        abs
      : 1       adsl
      : 2     adolfo
      : 5    aguilar
      : 6      aitor
      : Name: words, dtype: object

***** Select a sample of 5,000 words
      This is sample will be analyzed in detail and then a subset will be selected.

      This sample was selected in a way that it is reproducible.

      #+begin_src python :exports both :session words :results output
        word_pool_sample = word_pool.sample_pool(n=5000)
        print(word_pool_sample.size)
        print(word_pool_sample.head())
      #+end_src

      #+RESULTS:
      : 5000
      : 6215     atestiguar
      : 40259    penalmente
      : 6817        azoemia
      : 11728        chitar
      : 31861        ladero
      : Name: words, dtype: object
